import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/component/Navigation";
import Logo from "@/component/Logo";
import Footer from "@/component/Footer";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moda Wear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.className} flex flex-col min-h-screen`}>
        <nav className="flex justify-between items-center">
          <Logo />
          <Navigation />
        </nav>
        <main className="flex-1">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
